name = "quickapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = AcDJASQgNjNiYTVjMjYtMTEwYS00MjIzLTg1MjAtYmQ2M2U5M2EwYTY0NjRmYzc0NzRkNWQwNDAzZGJjZmFiOGRkNTJkMDU4NzE=
UPSTASH_REDIS_REST_URL = https://grateful-chimp-49353.upstash.io